subtask3: subtask3.cpp
	g++ -Ofast -o subtask3 subtask3.cpp /usr/local/lib/libopencv_core.so.2.4 /usr/local/lib/libopencv_highgui.so.2.4 /usr/local/lib/libopencv_imgproc.so.2.4 /usr/local/lib/libopencv_objdetect.so.2.4 
	./subtask3 ../dart8.jpg

