sobel: convolution.cpp
	g++ -o convolution convolution.cpp /usr/lib64/libopencv_core.so.2.4 /usr/lib64/libopencv_highgui.so.2.4 /usr/lib64/libopencv_imgproc.so.2.4
	./convolution coins3.png

hough: hough.cpp
	g++ -o hough hough.cpp /usr/lib64/libopencv_core.so.2.4 /usr/lib64/libopencv_highgui.so.2.4 /usr/lib64/libopencv_imgproc.so.2.4
	./hough coins1.png