man0: mandrill0Convert.cpp
	g++ -o mandrill0Convert mandrill0Convert.cpp /usr/lib64/libopencv_core.so.2.4 /usr/lib64/libopencv_highgui.so.2.4 /usr/lib64/libopencv_imgproc.so.2.4
	./mandrill0Convert
man2: mandrill2Convert.cpp
	g++ -o mandrill2Convert mandrill2Convert.cpp /usr/lib64/libopencv_core.so.2.4 /usr/lib64/libopencv_highgui.so.2.4 /usr/lib64/libopencv_imgproc.so.2.4
	./mandrill2Convert mandrill2.jpg
man1: mandrill1Convert.cpp
	g++ -o mandrill1Convert mandrill1Convert.cpp /usr/lib64/libopencv_core.so.2.4 /usr/lib64/libopencv_highgui.so.2.4 /usr/lib64/libopencv_imgproc.so.2.4
	./mandrill1Convert 