face: face.cpp
	g++ -o face face.cpp /usr/lib64/libopencv_core.so.2.4 /usr/lib64/libopencv_highgui.so.2.4 /usr/lib64/libopencv_imgproc.so.2.4 /usr/lib64/libopencv_objdetect.so.2.4 
	./face dart5.jpg

face1: face1.cpp
	g++ -o face1 face1.cpp /usr/local/lib/local/libopencv_core.so.2.4 /usr/lib/local/libopencv_highgui.so.2.4 /usr/lib/local/libopencv_imgproc.so.2.4 /usr/lib/local/libopencv_objdetect.so.2.4 
	./face1 dart0.jpg