con0: convolution.cpp
	g++ -o convolution convolution.cpp /usr/local/lib/libopencv_core.so.2.4 /usr/local/lib/libopencv_highgui.so.2.4 /usr/local/lib/libopencv_imgproc.so.2.4
	./convolution car1.png
con1: filter2d.cpp
	g++ -o filter2d filter2d.cpp /usr/local/lib/libopencv_core.so.2.4 /usr/local/lib/libopencv_highgui.so.2.4 /usr/local/lib/libopencv_imgproc.so.2.4
	./filter2d car2.png

