con0: convolution.cpp
	g++ -o convolution convolution.cpp /usr/local/lib/libopencv_core.so.2.4 /usr/local/lib/libopencv_highgui.so.2.4 /usr/local/lib/libopencv_imgproc.so.2.4
	./convolution car1.png

