convolution: convolution.cpp
	g++ -o convolution convolution.cpp /usr/lib64/libopencv_core.so.2.4 /usr/lib64/libopencv_highgui.so.2.4 /usr/lib64/libopencv_imgproc.so.2.4
	./convolution car1.png
median: filter2d.cpp
	g++ -o filter2d filter2d.cpp /usr/lib64/libopencv_core.so.2.4 /usr/lib64/libopencv_highgui.so.2.4 /usr/lib64/libopencv_imgproc.so.2.4
	./filter2d car2.png

